### ISSUE TITLE
Networking library

### ISSUE THREAD

**Issue by Aiosa** [pb173-2019/hello-world#47]
Find out which library will be used for networking
- well documented
- lightweight

**Comment by Shock3udt** [comment]
Thought about using QT networking library,
problems:
- it uses "sockets and signals" which I am not familiar with
- it is not realy light weight
- compiling with cmake might not be easy
advantages:
- It is in c++ not C
- it is well documented
- we may use qt GUI later for GUI

We also might use clasic berkley sockets (with winsocks), but
- it is in c - more error prone
- different version for different platform  (windows = winsock, posix + bsd = berkley)
advantages:
- it is pretty simple

**Comment by Shock3udt** [comment]
Agreed on QT
